DROP TABLE IF EXISTS users, category, event, request, compilation, event_compilation CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(250)                            NOT NULL,
    email VARCHAR(254)                            NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50)                             NOT NULL,
    CONSTRAINT PK_CATEGORY PRIMARY KEY (id),
    CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS event
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title              VARCHAR(120)                            NOT NULL,
    annotation         VARCHAR(2000)                           NOT NULL,
    category_id        BIGINT                                  NOT NULL,
    description        VARCHAR(7000)                           NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    initiator_id       BIGINT                                  NOT NULL,
    lat                NUMERIC                                 NOT NULL,
    lon                NUMERIC                                 NOT NULL,
    paid               BOOLEAN DEFAULT FALSE,
    request_moderation BOOLEAN DEFAULT TRUE,
    participant_limit  BIGINT  DEFAULT 0,
    confirmed_requests BIGINT  DEFAULT 0,
    views              BIGINT,
    state              VARCHAR(16),
    create_date        TIMESTAMP WITHOUT TIME ZONE,
    published_date     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT PK_EVENT PRIMARY KEY (id),
    CONSTRAINT FK_EVENT_USER
        FOREIGN KEY (initiator_id) REFERENCES users (id),
    CONSTRAINT FK_EVENT_CATEGORY
        FOREIGN KEY (category_id) REFERENCES category (id) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS request
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id     BIGINT                                  NOT NULL,
    requester_id BIGINT                                  NOT NULL,
    create_date  TIMESTAMP WITHOUT TIME ZONE,
    status       VARCHAR(16),
    CONSTRAINT PK_REQUEST PRIMARY KEY (id),
    CONSTRAINT FK_REQUEST_USER
        FOREIGN KEY (requester_id) REFERENCES users (id),
    CONSTRAINT FK_REQUEST_EVENT
        FOREIGN KEY (event_id) REFERENCES event (id)
);

CREATE TABLE IF NOT EXISTS compilation
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned BOOLEAN DEFAULT FALSE                   NOT NULL,
    title  VARCHAR(50)                             NOT NULL,
    CONSTRAINT PK_COMPILATION PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS event_compilation
(
    event_id       BIGINT NOT NULL,
    compilation_id BIGINT NOT NULL,
    CONSTRAINT PK_EVENT_COMPILATION PRIMARY KEY (event_id, compilation_id),
    CONSTRAINT FK_EVENT_EVENT_COMPILATION
        FOREIGN KEY (event_id) REFERENCES event (id),
    CONSTRAINT FK_COMPILATION_EVENT_COMPILATION
        FOREIGN KEY (compilation_id) REFERENCES compilation (id)
);